---
title: "Mittelwert"
output: html_document
---

<<<<<<< HEAD
Mittelwerte (kurz auch nur Mittel, in der Statistik oft auch Durchschnitt statt arithmetisches Mittel) treten in der Mathematik und insbesondere in der Statistik in inhaltlich unterschiedlichen Kontexten auf. Allgemein gilt, dass jedem Mittelwert eine Vorschrift zugrunde liegt, mit der man aus zwei oder mehr Zahlen eine weitere berechnet, die zwischen den gegebenen Zahlen liegt.

In der Statistik wird außerdem oft als Mittelwert der Erwartungswert angedeutet, ein so genannter Lageparameter einer Häufigkeits- oder Wahrscheinlichkeitsverteilung, der die Lage der Elemente einer Stichprobe oder Grundgesamtheit in Bezug auf die Messskala beschreibt.
=======
##Mittelwert {m}
meanmath.stat.
average
mean value
average value
midpointmath.stat.
Mittelwert {m} <MW>
mean score
arithmetischer Mittelwert {m}
arithmetic mean (value)
arithmetic averagemath.stat.
geometrischer Mittelwert {m} <GM>
geometric meanmath.stat.
gewichteter Mittelwert {m}
weighted average
gewogener Mittelwert {m}
mean average
gleitender Mittelwert {m}
rolling meanmath.stat.
moving averagemath.stat.
harmonischer Mittelwert {m}
harmonic mean <HM>math.
mengengewichteter Mittelwert {m}
volume-weighted mean value
quadratischer Mittelwert {m}
root mean square
quadratischer Mittelwert {m} <QM, QMW>
quadratic mean <QM>electr.stat.
Mittelwert bilden (aus)
to average (over)
einfacher gleitender Mittelwert {m}
simple moving average <SMA>
exponentiell geglätteter Mittelwert {m}
exponential moving average <EMA>
Rückkehr {f} zum Mittelwert
mean-revertingmath.
Mittelwert null, Varianz eins
zero mean, unit variancemath.stat.
>>>>>>> 461ad78ac8db329e05b7910577fe11f000e50966
